import styles from '@/app/globals.css';


export const metadata = {
  title: 'Tutora.IA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
          {children}
      </body>
    </html>
  )
}