import styles from '@/app/globals.css';
import SideNavBar from '../components/sideNavBar.component/sideNavBar';

export const metadata = {
  title: 'Tutora.IA',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <body>
          <SideNavBar />
          {children}
      </body>
    </html>
  )
}