import styles from '@/app/globals.css';
import SideNavBar from '../components/sideNavBar.component/sideNavBar';
import { ApplicationContext } from '../components/context.component/ApplicationProvider';


export const metadata = {
  title: 'Tutora.IA',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <body>
        {/* <ApplicationContext> */}
          <SideNavBar />
          {children}
        {/* </ApplicationContext> */}
      </body>
    </html>
  )
}