
import '../globals.css'
import style from './denuncia/page.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={style.body}>{children}</body>
    </html>
  )
}
